#ifndef _WORKERS_CONSTANTS_H_
#define  _WORKERS_CONSTANTS_H_

enum Gatherer{
  GATHERER_FARMER, GATHERER_LUMBERJACK, GATHERER_MINER
};

enum Producer{
  PRODUCER_COOKER, PRODUCER_CARPENTER, PRODUCER_GUNSMITH
};

enum ProducerPoints{
  PRODUCER_PONTS_COOKER = 5, PRODUCER_PONTS_CARPENTER = 2,
  PRODUCER_PONTS_GUNSMITH = 3
};

enum ResourceNeeded{
  RESOURCE_NEEDED_COOKER_WHEAT = 2, RESOURCE_NEEDED_COOKER_COAL = 1,
  RESOURCE_NEEDED_CARPENTER_WOOD = 3, RESOURCE_NEEDED_CARPENTER_IRON = 1,
  RESOURCE_NEEDED_GUNSMITH_COAL = 2, RESOURCE_NEEDED_GUNSMITH_IRON = 2
};

#endif
